Plugin:
  check-for-updates: true
  use-metrics: true

Config:
  tag: '&6&lU&a&lClans &8>>'
  date-format: 'dd/MM/yyyy HH:mm'
  debug_errors: false
  confirm: 'CONFIRM'
  confirm_case_sensitive: true
  teleport_delay: 3
  logs:
    clan: true
    stacktrace: true
#
#Placeholders with PlaceholderAPI:
# %uclans_hasclan%
# %uclans_hasclan_formated%
# %uclans_tag_nocolor%
# %uclans_tag_color%
# %uclans_tag_formated%
# %uclans_tag_formated_level%
# %uclans_level_identifier%
# %uclans_desc_nocolor%
# %uclans_desc_color%
# %uclans_leader%
# %uclans_creation_date%
# %creation_date_formated%
# %uclans_clanid%
# %uclans_clan_kills%
# %uclans_clan_deaths%
# %uclans_clan_souls%
# %uclans_clan_kdr%
# %uclans_clan_home%
# %uclans_clan_members%
# %uclans_clan_onlinemembers%
# %uclans_player_kills%
# %uclans_player_deaths%
# %uclans_player_souls%
# %uclans_player_kd%
# %uclans_count_members%

Events:
  liquid_flow:
    disable: true
  piston:
    disable: true
  explosion:
    creeper: true
    tnt: true
    others: true
    ender_crystal: true
    fireball: true
  place:
    enabled: true
    blocked_list:
    - 'TNT'
    - 'POWERED_RAIL'
  mobs:
    enabled: true
    blocked_events:
    - 'NATURAL'

Survival_mode: #terrains
  enabled: true
  clan_bases: true
  only_edit_claimed: true
  chunks_start_clan: 4
  chunks_by_player: 1
  chunks_max_clan: 10
  chunk_price: 100000.0
  enabled_worlds: 'world'
  use_material_claim: true
  use_material_claim_all: false
  material_claim: 'TORCH'
  bypass_permission_edit: 'player.bypass.perm.edit' #Edit all terrains, protected or not. Permission for STAFFS.
  rtp:
    enabled: true
    use_delay: 120
    rangemax: 2500
    rangemin: -2500
    block_if_empty: 'STONE'
  Title:
    chunks:
      enabled: true
      message: '&cLand of the clan %clan_tag%'
      sub: 'Desc: %clan_desc%'
      fadein: 1
      stay: 3
      fadeout: 1
  Actionbar:
    chunks:
      enabled: true
      message: '&eLand of the clan &b%clan_tag%'
  Chat:
    chunks:
      enabled: true
      message: '&eLand of the clan &b%clan_tag%'

Hologram:
  enabled: true
  prefix: 'uc_'
  maxlist: 10
  ajust-Y: 2.0
  header: '&d&lTop 10 Clans'
  footer: '&eFor more use &b/clan list'
  format: '&6&l%num%° &7- &a%clan_tag% &7- %clan_members_size% member(s) &7- &b%clan_kills%&8/&b%clan_deaths% &8(%clan_kdr%)'
  tasks:
    holosave_start: 300
    holosave: 300
    holorefresh_start: 5
    holorefresh: 305

Cosmetic:
  item:
    material: 'STAINED_GLASS_PANE'
    data: 7
    amount: 1
    name: ' '
    flags:
    - 'HIDE_ENCHANTS'

Gui:
  help_gui: true
  hasclan: 'index_hasclan'
  noclan: 'index_noclan'

Clan:
  disabled_command_worlds:
  - 'disabled_worlds'
  disabled_command_regions:
  - 'disabled_worlds'
  forced_ff_worlds:
  - 'disabled_worlds'
  forced_ff_regions:
  - 'worlds'
  invite:
    max_time_seconds: 60
    allowed_chars: "[0-9a-zA-Z]*"
  chat:
    format: ' &d%uclans_level_identifier% &5%player%&d: &d%chat_message%'
  verify:
    always_verified: true
  kills:
    neutral: 1
    ally: 2
    rival: 3
  match:
    rival:
      add: 'add'
      remove: 'remove'
    ally:
      add: 'add'
      remove: 'remove'
  prices:
    enabled: true #Default VAULT, if "false" does not charge player values.
    desc: 0.0
    create: 1000.0
    invite: 0.0
    deny: 0.0
    join: 0.0
    leave: 0.0
    kick: 0.0
    promote: 0.0
    demote: 0.0
    disband: 0.0
    sethome: 0.0
    home: 0.0
    modtag: 0.0
    rival: 0.0 #ADD OR REMOVE
    ally: 0.0 #ADD OR REMOVE
    togglechat: 0.0
    toggleff: 0.0
    rtp: 0.0
    base: 0.0
    unclaimall: 0.0
    unclaim: 0.0
    war: 0.0
  limits:
    amount_by_player: 2
    max_by_clan: 10
  task:
    update_list:
      start: 5
      next: 300
    update_invite:
      start: 60
      next: 60
    save_playerdata:
      start: 300
      next: 600
    save_clandata:
      start: 300
      next: 600
  level:
    leader:
      identifier: '&6**&r'
    mod:
      identifier: '&2*&r'
  list:
    max_pag: 10
    max_list: 10
    use_next_prev: false
  tag:
    allow_color: true
    min_chars: 2
    max_chars: 8
    allowed_chars: "[0-9a-zA-Z]*"
    default_color: '&8'
    start: '&f['
    end: '&f]&r'
    noclan_formated: '&4WITHOUT CLAN'
  desc:
    allow_color: true
    min_chars: 2
    max_chars: 64
    allowed_chars: "[0-9a-zA-Z \\-'_]*"
    default_color: '&8'

Messages:
  hologram:
    disabled: '%tag% &cHolograms are off.'
    not_exists: '%tag% &cThis hologram does not exist'
    teleported: '%tag% &eYou have been teleported to the hologram &b%id%'
    header: '&d&lList of Holograms:'
    format_checked: ' &7&m%num%° &8&m- &7&m%id%&r &a&lOK'
    format_unchecked: ' &a%num%° &7- &b%id% &7- &b%location% &8(%world%&8)'
    footer: ''
    empty: ' &cNo status to show.'
    wait: ' &ewait....'
  comum:
    empty: ' '
    special_nopaste: '%tag% &cThere was an error with this, please try again!'
    error_special_item: '%tag% &cAn error occurred with this, please notify an administrator!'
    error_special_item_command: '%tag% &cUse &4/uclan item <player> <item> <amount>'
    special_incooldown: '%tag% &eWait %sec% sec to use this again!'
    special_used: '%tag% &eYou used a %item%'
    special_noblocks: '%tag% &cThe item was not used because it has but nothing to clean!'
    specialitem_received: '%tag% &eYou received &b%amount% %item%'
    teleport_dont_move: '%tag% &ePreparing teleport, do not move by %sec% sec.'
    teleport_moved: '%tag% &cYou moved and the teleport was canceled!!!'
    teleport_true: '%tag% &eYou were teleported!'
    cooldown_teleport: '%tag% &cWait %time% sec. to use again.'
    dont_world_claim: '%tag% &cYou are not in a world of terrain.'
    dont_place_item: '%tag% &cYou cannot use this item.'
    error_unclaimchunk: '%tag% &cThere was an error declaiming this terrain.'
    not_owner: '%tag% &cYou are not the owner of this land.'
    max_claimed: '%tag% &cYouve already claimed as many %max% terrains.'
    chunk_has_notowner: '%tag% &cThis land has no owner.'
    chunk_has_owner: '%tag% &cThis land already has owner.'
    dont_have_claim_clan: '%tag% &cThis clan does not exist or does not have land.'
    location_blocked: '%tag% &cThe location &b%coord% &cis blocked for teleport.'
    dont_have_claim: '%tag% &cYour clan has no land.'
    error_unclaimallchunk: '%tag% &cError in declaiming the lands.'
    land_dont_break: '%tag% &cYou cant break here ...'
    land_dont_place: '%tag% &cYou cant build here ...'
    land_dont_edit: '%tag% &cYou cannot edit here ...'
    survival_disabled: '%tag% &cGame mode disabled.'
    action_removed: '%tag% &cAll actions have been deleted.'
    action_disband_error: '%tag% &cYou did not enter a confirmation and the action was canceled!'
    error_startaction: '%tag% &cThere was an error running this.'
    command_by_player: '%tag% &cThis command must be used by a player.'
    command_by_console: '%tag% &cThis command must be used by the Console.'
    disabled_world_command: '%tag% &cClan commands are turned off in this world.'
    dont_money: '%tag% &cYou need to &a$%amount% &cfor this.'
    debited_money: '%tag% &eIt was debited &a%amount% &eyour account.'
    help_header: '&d&lHelp with Clan:'
    help_land_header: '&d&lLand help:'
    help_clan_header: '&d&lClan Help:'
    help_uclan_header: '&4&lAdmin Clan Help:'
    help_profile_header: '&d&lProfile of &a%player%&d&l:'
    help_stats_header: '&d&lClan Status &a%clan_tag%&d&l:'
    list_header: '&d&lList of Clans: &8(rank/tag/desc/kdr/members)'
    list_sub_header: ' &8Showing %cur%/%amount% of %total% (Page: %pag_cur%/%pag_max%)'
    empty_list: ' &cNo Clan in this list.'
    error_to_execute: '%tag% &cAn error has occurred, please try again.'
    no_permission: '%tag% &cYou do not have permission'
    player_have_clan: '%tag% &cYou already have a clan.'
    player_donthave_clan: '%tag% &cYou dont have a Clan.'
    another_player_donthave_clan: '%tag% &cThis player does not have a clan.'
    tag_in_use: '%tag% &cThis TAG is already in use.'
    error_character: '%tag% &cThis contains invalid characters.'
    error_create: '%tag% &cError creating a new Clan, try again.'
    error_delete: '%tag% &cError deleting the Clan, try again.'
    error_sethome: '%tag% &cError when setting the Clan HOME, try again.'
    dont_have_home: '%tag% &cYour Clan does not have a set home.'
    dont_leader: '%tag% &cYou are not the leader of the Clan.'
    hasglobal_ff: '%tag% &eGlobal friendly fire is now on!'
    clanpvp_disabled: '%tag% &cClan PVP is now turned off.'
    error_modtag: '%tag% &cError when changing the clan TAG.'
    error_moddesc: '%tag% &cError changing the Clan description.'
    clan_not_found: '%tag% &cClan with this TAG does not exist.'
    tag_equals: '%tag% &cUnchanged TAG, appears to be the same.'
    leave_is_leader: '%tag% &cYou are the Clan Leader, to leave use &b/clan disband&c and you will delete the Clan ...'
    error_leave: '%tag% &cError when leaving the Clan, try again.'
    player_offline: '%tag% &cThe player is offline or does not exist!'
    invited_has_clan: '%tag% &cThis player already has a Clan.'
    error_invite: '%tag% &cError inviting player, please try again.'
    already_invite: '%tag% &cThere is already an invitation for this player.'
    invite_expired: '%tag% &cYour invitation to join the Clan &f%clan_tag% &cehas expired.'
    invite_donthave: '%tag% &cYou have no invitations.'
    invite_error_recuse: '%tag% &cError declining invitation.'
    invite_error_join: '%tag% &cError entering the clan, try again.'
    dont_in_your_clan: '%tag% &cThis player is not in your Clan.'
    error_kick: '%tag% &cError kicking the player.'
    dont_kick_leader: '%tag% &You cannot expel the Clan Leader.'
    already_mod: '%tag% &cThis player is already a moderator.'
    dont_mod: '%tag% &cThis player is not a moderator.'
    promote_error: '%tag% &cError promoting the player, try again ...'
    demote_error: '%tag% &cError demoting this player, try again ...'
    dont_permission_to_kick: '%tag% &cYou cannot expel players.'
    dont_permission_to_promote: '%tag% &cYou cannot promote players.'
    is_leader: '%tag% &cThis player is the Clan Leader.'
    empty_chat_help: '%tag% &cError, Use &b/. <message>'
    is_your_clan: '%tag% &cThis is your Clan.'
    already_rival: '%tag% &cThis Clan is already a rival.'
    is_ally: '%tag% &cThis Clan is already an ally.'
    dont_rival: '%tag% &cThis Clan is not a rival.'
    rival_add_error: '%tag% &cError adding rival.'
    rival_remove_error: '%tag% &cError removing rival.'
    already_ally: '%tag% &cThis Clan is already an ally.'
    is_rival: '%tag% &cThis Clan is already an ally.'
    dont_ally: '%tag% &cThis Clan is not an ally.'
    ally_add_error: '%tag% &cError adding ally.'
    ally_remove_error: '%tag% &cError removing ally.'
    max_members: '&cThis Clan already has the maximum number of players.'
    nodesc_tag: '&c<Without description!>'
    nothing_on_list: '&cNothing here'
    none: '&cNo one'
    invite:
      invited: '%tag% &eHas invited &a%invited%&e. &8(%invalid% invalid)'
      offline: ' &7 - Offlines: &c%offline%'
      hasclan: ' &7 - Has Clan: &c%hasclan%'
    error_verify: '&cError when trying, check the clan'
    rival_header: '&d&lList of Rivals. &8(tag/kdr/members)'
    ally_header: '&d&lList of Allies. &8(tag/kdr/members)'
    info_header: '&d&lClan Information &8%clan_tag%&d&l:'
    info_format:
    - ' &7Tag: &b%clan_tag%'
    - ' &7Desc: &b%clan_desc%'
    - ' &7Leader: &b%clan_leader%'
    - ' &7Creation date: &b%clan_creation_date%'
    - ' &7Verified: &b%clan_verified%'
    - ' &7Kdr: &b%clan_kills%&8/&b%clan_deaths% &8(%clan_kdr%)'
    - ' &7Members: &b%clan_members%'
    - ' &7Allies: &b%clan_ally%'
    - ' &7RRivais: &b%clan_rival%'
    - ' &7Lands: &b%clan_chunks%'
    - ''
    profile_format:
    - ' &7Nname: &b%player_name%'
    - ' &7Clan: &b%clan_tag%'
    - ' &7Clan leader: &b%clan_leader%'
    - ' &7Kdr: &b%player_kills%&8/&b%player_deaths% &8(%player_kdr%)'
    - ' &7Entry into: &b%player_join_date%'
    - ' &7Last Seen: &b%player_seen_date%'
    - ' '
    stats_format:
    - ' &7Tag: &b%clan_tag%'
    - ' &7Creation date: &b%clan_creation_date%'
    - ' &7Verified: &b%clan_verified%'
    - ' &7Clan Kdr: &b%clan_kills%&8/&b%clan_deaths% &8(%clan_kdr%)'
    - ' &7Members:'
    landinfo_header: '&d&lLand Information:'
    landinfo_format:
    - ' &7Lands: &b%chunk%'
    - ' &7Clan owner: &b%chunk_owner%'
    landlist_header: '&d&lLLista de seus terrenos:'
    landlist_format:
    - ' &7Lands: &b%number%'
    - ' &7Chunks: &b%chunk%'
    stats_member_format: '  &7&a%list_player% &7- &b%list_player_role% &7- &b%list_player_kills%&8/&b%list_player_deaths% &8(%list_player_kdr%) &7[%list_player_seen_date%]'
    new_ally: '%tag% &c&l! &eA new alliance was formed with the clan &a%clan_tag%'
    removed_ally: '%tag% &c&l! &eThe alliance with the clan &a%clan_tag% &ehas removed.'
    ff_changed: '%tag% &c&l! &eThe friendly fire is &b%value%.'
    globalff_changed: '%tag% &c&l! &eGlobal friendly fire is &b%value%.'
    new_join: '%tag% &c&l! &eThe player &a%player% &eentered the Clan.'
    new_kick: '%tag% &c&l! &eThe player &a%player% &ewas expelled from the Clan.'
    new_rival: '%tag% &c&l! &eNew rivalry with the Clan &a%clan_tag%'
    removed_rival: '%tag% &c&l! &eThe rivalry with the Clan &a%clan_tag% &ewas undone.'
    clan_deleted: '%tag% &c&l! &eThe Clan &b%clan_tag% &ewas deleted by &a%player%.'
    clan_created: '%tag% &c&l! &eA new Clan &b%clan_tag% &ewas created by &a%player%.'
    clan_verify_changed: '%tag% &c&l! &eThe clan was changed to &a%value%.'
    new_promote: '%tag% &c&l! &eThe player &a%player% &egot promoted.'
    new_demote: '%tag% &c&l! &cThe player &a%player% &ewas demoted.'
  traduction:
    is_on: '&a&lOnline'
    is_off: '&4&lOffline'
    player: 'player'
    players: 'players'
    is_yes: '&b&lYES'
    is_no: '&c&lNOT'
  json:
    clan_ally_rival_list_format:
        raw_text: ' &8%clan_tag% &7- &b%clan_kdr% &7- &b%clan_members_count%'
        hover_text: '&aShows Clan information.'
        click_type: 'SUGGEST_COMMAND'
        click_action: '/clan info %clan_tag_nocolor%'
    clan_list_format:
        raw_text: ' &a%clan_rank%° &7- &8%clan_tag% &7- &f%clan_desc% &7- &b%clan_kdr% &7- &b%clan_members_count%'
        hover_text: '&aClick show info of clan.'
        click_type: 'SUGGEST_COMMAND'
        click_action: '/clan info %clan_tag_nocolor%'
    list_next:
        raw_text: ' &bNext page >>'
        hover_text: '&aClick to see the next page.'
        click_type: 'RUN_COMMAND'
        click_action: '/clan list %next_page%'
    list_prev:
        raw_text: ' << &bPrevious page'
        hover_text: '&aClick to see the previous page.'
        click_type: 'RUN_COMMAND'
        click_action: '/clan list %prev_page%'
    list_controler:
        raw_text: ' << &bPrevious page'
        hover_text: '&aClick to see the previous page.'
        click_type: 'RUN_COMMAND'
        click_action: '/clan list %prev_page%'
    clan_deleted:
        raw_text: ' &a%clan_rank%° &7- &c&mClan deletado!'
        hover_text: '&cSoon it will leave this list!'
        click_type: ''
        click_action: ''
    invite_received:
        raw_text: ' &c&l! &eYou have received an invitation to join the Clan &f%clan_tag%&e, the invitation expires on &b%sec_expires% sec&e.'
        raw_base_color: 'YELLOW'
        hover_text: '&aClick to ACCEPT or DENY.'
        click_type: 'SUGGEST_COMMAND'
        click_action: '/clan <join/deny> %clan_tag_nocolor%'
    invite_accept:
        raw_text: ' &7- To accept use &b/clan join %clan_tag_nocolor%'
        hover_text: '&aClick to accept.'
        click_type: 'SUGGEST_COMMAND'
        click_action: '/clan join %clan_tag_nocolor%'
    invite_deny:
        raw_text: ' &7- To deny use &b/clan deny %clan_tag_nocolor%'
        hover_text: '&cClick to deny the request.'
        click_type: 'SUGGEST_COMMAND'
        click_action: '/clan deny %clan_tag_nocolor%'
