name: UClans
main: me.ulrich.clans.Clans
version: 1.1.7
author: UlrichBR
description: The best and most complete system of clans and lands.
api-version: 1.16
softdepend: [Vault, PlaceholderAPI, PrototolLib]
commands:
   uclan:
      description: Open the help staff menu.
      usage: /<command>
      aliases: [uclans, uc]
   clan:
      description: Open the help player menu.
      usage: /<command>
      aliases: [clans, c]
   clanchat:
      description: Use Clan chat.
      usage: /<Command> help
      aliases: [.]
Permissions:
  uclans.admin.*:
    children: 
      uclans.admin.spawnholo: true
      uclans.admin.despawnholo: true
      uclans.admin.listholos: true
      uclans.admin.tpholo: true
      uclans.admin.reloadholos: true
      uclans.admin.help: true
      uclans.admin.globalff: true
      uclans.admin.delete: true
      uclans.admin.verify: true
      uclans.admin.rtp: true
      uclans.admin.reload: true
      uclans.admin.wand: true
      uclans.admin.clearwand: true
      uclans.admin.addregion: true
      uclans.admin.removeregion: true
      uclans.admin.listregions: true
      uclans.admin.tpregion: true
  uclans.player.*:
    children: 
      uclans.player.help: true
      uclans.player.create: true
      uclans.player.desc: true
      uclans.player.name: true
      uclans.player.disband: true
      uclans.player.leave: true
      uclans.player.invite: true
      uclans.player.join: true
      uclans.player.deny: true
      uclans.player.kick: true
      uclans.player.promote: true
      uclans.player.demote: true
      uclans.player.sethome: true
      uclans.player.home: true
      uclans.player.chat: true
      uclans.player.ff: true
      uclans.player.modtag: true
      uclans.player.list: true
      uclans.player.info: true
      uclans.player.stats: true
      uclans.player.profile: true
      uclans.player.rival: true
      uclans.player.rivalries: true
      uclans.player.ally: true
      uclans.player.alliances: true
